### PR TITLE
enhance: support for tab key in webclient

### PR DESCRIPTION
**Pull request by sinux-l5d**
As mentioned in #8, I added support for the tab key.

It adds 4 spaces, not the tab character. Maybe that's not the most appropriate way.

We could improve that even more:
* it adds 4 spaces but removes on space at a time with delete key
* you can't indent a block of code

I forked from `master` but opened the merge request on `next`, so it includes your commit "bin v2.2.0". If that's not what you want, let me know.

### CODE REVIEW

**Comment by sinux-l5d** [comment]
The build check fails against the Rust code (that I did not touched). Apparently, some `.to_string()` is unnecessary

**Comment by WantGuns** [comment]
> The build check fails against the Rust code (that I did not touched). Apparently, some `.to_string()` are unnecessary

Apparently the latest rust / clippy version gave some more insights. Fixed that now.

Could you rebase and squash your commits ?

**Comment by sinux-l5d** [comment]
Well, I think it's good to go. Let me know if something's wrong :)

**Comment by WantGuns** [comment]
Thanks !

**Pull request merged**
